# Access the id_github file from Secret Manager, and setup SSH
steps:
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp known_hosts.github /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh
 
# Clone the repository
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - --recurse-submodules
  - git@github.com:adityak-CSWG/orderdata.git
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--no-cache', '--tag', 'us-east4-docker.pkg.dev/gc-proj-devis-poc-6586/cloud-run-source-deploy/intern-dashboard:latest', '.']
  
  # Push the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east4-docker.pkg.dev/gc-proj-devis-poc-6586/cloud-run-source-deploy/intern-dashboard:latest']
  
  # Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
      'run', 'deploy', 'intern-dashboard',
      '--image', 'us-east4-docker.pkg.dev/gc-proj-devis-poc-6586/cloud-run-source-deploy/intern-dashboard:latest',
      '--region', 'us-east4',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-env-vars', 'GOOGLE_CLOUD_PROJECT=gc-proj-devis-poc-6586, GOOGLE_APPLICATION_CREDENTIALS="{  "delegates": [],  "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/poc-test-git@gc-proj-devis-poc-6586.iam.gserviceaccount.com:generateAccessToken",  "source_credentials": {    "account": "",    "client_id": "764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com",    "client_secret": "d-FL95Q19q7MQmFpd7hHD0Ty",    "refresh_token": "1//05sR2QjKDfBP-CgYIARAAGAUSNwF-L9Ir3c7RxCsY-d0LlFJWt0rbalbMIOGEF2g3rkq5qXXzRY23uzhXCARBzSPumujIhXQZWwA",    "type": "authorized_user",    "universe_domain": "googleapis.com"  },  "type": "impersonated_service_account"}"',
      '--network', 'projects/gc-proj-nw-shnp-8211/global/networks/nonprod-core-sharedvpc',
      '--subnet', 'projects/gc-proj-nw-shnp-8211/regions/us-east4/subnetworks/nonprod-core-subnet'
    ]

images:
  - 'us-east4-docker.pkg.dev/gc-proj-devis-poc-6586/cloud-run-source-deploy/intern-dashboard:latest'

availableSecrets:
  secretManager:
  - versionName: projects/998524737689/secrets/private-github-key-intern/versions/latest
    env: 'SSH_KEY'

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: projects/gc-proj-devis-poc-6586/serviceAccounts/poc-test-git@gc-proj-devis-poc-6586.iam.gserviceaccount.com
